//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WHBillContrast.WHBillContrastWS
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "WebServiceSoap", Namespace = "http://mflex.com.cn/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;

        private System.Threading.SendOrPostCallback CanLoginOperationCompleted;

        private System.Threading.SendOrPostCallback InsertLogOperationCompleted;

        private bool useDefaultCredentialsSetExplicitly;

        /// <remarks/>
        public WebService()
        {
            this.Url = "http://mycmesflexpda.mflex.com.cn/whbillcontrastws/webservice.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        public new string Url
        {
            get
            {
                return base.Url;
            }
            set
            {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true)
                            && (this.useDefaultCredentialsSetExplicitly == false))
                            && (this.IsLocalFileSystemWebService(value) == false)))
                {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }

        public new bool UseDefaultCredentials
        {
            get
            {
                return base.UseDefaultCredentials;
            }
            set
            {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;

        /// <remarks/>
        public event CanLoginCompletedEventHandler CanLoginCompleted;

        /// <remarks/>
        public event InsertLogCompletedEventHandler InsertLogCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mflex.com.cn/HelloWorld", RequestNamespace = "http://mflex.com.cn/", ResponseNamespace = "http://mflex.com.cn/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld()
        {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void HelloWorldAsync()
        {
            this.HelloWorldAsync(null);
        }

        /// <remarks/>
        public void HelloWorldAsync(object userState)
        {
            if ((this.HelloWorldOperationCompleted == null))
            {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }

        private void OnHelloWorldOperationCompleted(object arg)
        {
            if ((this.HelloWorldCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mflex.com.cn/CanLogin", RequestNamespace = "http://mflex.com.cn/", ResponseNamespace = "http://mflex.com.cn/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CanLogin(ref ResultObj Result, string Username, string Password)
        {
            object[] results = this.Invoke("CanLogin", new object[] {
                        Result,
                        Username,
                        Password});
            Result = ((ResultObj)(results[1]));
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void CanLoginAsync(ResultObj Result, string Username, string Password)
        {
            this.CanLoginAsync(Result, Username, Password, null);
        }

        /// <remarks/>
        public void CanLoginAsync(ResultObj Result, string Username, string Password, object userState)
        {
            if ((this.CanLoginOperationCompleted == null))
            {
                this.CanLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCanLoginOperationCompleted);
            }
            this.InvokeAsync("CanLogin", new object[] {
                        Result,
                        Username,
                        Password}, this.CanLoginOperationCompleted, userState);
        }

        private void OnCanLoginOperationCompleted(object arg)
        {
            if ((this.CanLoginCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CanLoginCompleted(this, new CanLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mflex.com.cn/InsertLog", RequestNamespace = "http://mflex.com.cn/", ResponseNamespace = "http://mflex.com.cn/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertLog(ref ResultObj Result, SMS_VENDORVWAREobj SMS_VENDORVWAREobjS)
        {
            object[] results = this.Invoke("InsertLog", new object[] {
                        Result,
                        SMS_VENDORVWAREobjS});
            Result = ((ResultObj)(results[1]));
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void InsertLogAsync(ResultObj Result, SMS_VENDORVWAREobj SMS_VENDORVWAREobjS)
        {
            this.InsertLogAsync(Result, SMS_VENDORVWAREobjS, null);
        }

        /// <remarks/>
        public void InsertLogAsync(ResultObj Result, SMS_VENDORVWAREobj SMS_VENDORVWAREobjS, object userState)
        {
            if ((this.InsertLogOperationCompleted == null))
            {
                this.InsertLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertLogOperationCompleted);
            }
            this.InvokeAsync("InsertLog", new object[] {
                        Result,
                        SMS_VENDORVWAREobjS}, this.InsertLogOperationCompleted, userState);
        }

        private void OnInsertLogOperationCompleted(object arg)
        {
            if ((this.InsertLogCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertLogCompleted(this, new InsertLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }

        private bool IsLocalFileSystemWebService(string url)
        {
            if (((url == null)
                        || (url == string.Empty)))
            {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024)
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
            {
                return true;
            }
            return false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://mflex.com.cn/")]
    public partial class ResultObj
    {

        private string resultCodeField;

        private string resultMesgField;

        /// <remarks/>
        public string ResultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }

        /// <remarks/>
        public string ResultMesg
        {
            get
            {
                return this.resultMesgField;
            }
            set
            {
                this.resultMesgField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://mflex.com.cn/")]
    public partial class SMS_VENDORVWAREobj
    {

        private int vQTYField;

        private string vCUSTOMERPNField;

        private string vMPNField;

        private string vCOOCNField;

        private int wQTYField;

        private string wCUSTOMERPNField;

        private string wMPNField;

        private string wCOOCNField;

        private string oPERATORSField;

        /// <remarks/>
        public int VQTY
        {
            get
            {
                return this.vQTYField;
            }
            set
            {
                this.vQTYField = value;
            }
        }

        /// <remarks/>
        public string VCUSTOMERPN
        {
            get
            {
                return this.vCUSTOMERPNField;
            }
            set
            {
                this.vCUSTOMERPNField = value;
            }
        }

        /// <remarks/>
        public string VMPN
        {
            get
            {
                return this.vMPNField;
            }
            set
            {
                this.vMPNField = value;
            }
        }

        /// <remarks/>
        public string VCOOCN
        {
            get
            {
                return this.vCOOCNField;
            }
            set
            {
                this.vCOOCNField = value;
            }
        }

        /// <remarks/>
        public int WQTY
        {
            get
            {
                return this.wQTYField;
            }
            set
            {
                this.wQTYField = value;
            }
        }

        /// <remarks/>
        public string WCUSTOMERPN
        {
            get
            {
                return this.wCUSTOMERPNField;
            }
            set
            {
                this.wCUSTOMERPNField = value;
            }
        }

        /// <remarks/>
        public string WMPN
        {
            get
            {
                return this.wMPNField;
            }
            set
            {
                this.wMPNField = value;
            }
        }

        /// <remarks/>
        public string WCOOCN
        {
            get
            {
                return this.wCOOCNField;
            }
            set
            {
                this.wCOOCNField = value;
            }
        }

        /// <remarks/>
        public string OPERATORS
        {
            get
            {
                return this.oPERATORSField;
            }
            set
            {
                this.oPERATORSField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CanLoginCompletedEventHandler(object sender, CanLoginCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CanLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CanLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }


    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void InsertLogCompletedEventHandler(object sender, InsertLogCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal InsertLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }


    }
}

#pragma warning restore 1591